Program Factorial;

var int x;

func recursive_fac (var int x;): int {
  if (x == 1) {
    return x;
  }
  return x * recursive_fac(x - 1);
}

func iterative_fac(var int x;): int 
  var int product;
  var int i;
{
  product = 1;
  i = 1;
  while (i <= x) {
    product = product * i;
    i = i + 1;
  }
  return product;
}

main() {
  x = recursive_fac(7);
  print(x);
  x = iterative_fac(7);
  print(x);
}